//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckpointGroup
    {
        public CheckpointGroup()
        {
            this.Checkpoints = new HashSet<Checkpoint>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Checkpoint> Checkpoints { get; set; }
    }
}
