//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inspection
    {
        public Inspection()
        {
            this.InspectionCheckpoints = new HashSet<InspectionCheckpoint>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<double> Score { get; set; }
        public int UserId { get; set; }
        public int VehicleId { get; set; }
    
        public virtual User User { get; set; }
        public virtual Vehicle Vehicle { get; set; }
        public virtual ICollection<InspectionCheckpoint> InspectionCheckpoints { get; set; }
    }
}
