//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleInspectionApplication.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Checkpoint
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Checkpoint()
        {
            this.InspectionCheckpoints = new HashSet<InspectionCheckpoint>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string VehicleType { get; set; }
        public Nullable<int> Grade { get; set; }
        public int CkpGroupId { get; set; }
    
        public virtual CheckpointGroup CheckpointGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InspectionCheckpoint> InspectionCheckpoints { get; set; }
    }
}
